from BaseClasses import Item

class ArmoredCore6Item(Item):
    game: str = "Armored Core 6"

items = [
    ["beginner equipment", False, False, False, 1],
    ["beginner equipment 2", False, False, True, 1],
    ["beginner equipment 3", False, False, False, 1],
    ["beginner equipment 4", False, False, False, 1],
    ["beginner equipment 5", False, False, False, 1],
    ["beginner equipment 6", False, False, False, 1],
    ["intermediate", False, False, False, 2],
    ["intermediate 2", False, False, False, 2],
    ["intermediate 3", False, False, False, 2],
    ["intermediate 4", False, True, False, 2],
    ["intermediate 5", True, False, False, 2],
    ["intermediate 6", False, False, True, 2],
    ["intermediate 7", False, False, False, 3],
    ["watchpoint", True, True, False, 3],
    ["watchpoint 2", False, True, False, 3],
    ["watchpoint 3", False, False, False, 3],
    ["watchpoint 4", False, False, False, 3],
    ["watchpoint 5", False, False, False, 3],
    ["watchpoint 6", False, False, False, 3],
    ["infiltrate", False, False, False, 3],
    ["ocean crossing", False, True, False, 4],
    ["ocean crossing 2", False, False, False, 4],
    ["ocean crossing 3", True, False, False, 4],
    ["ocean crossing 4", False, False, False, 4],
    ["ocean crossing 5", False, False, False, 4],
    ["ocean crossing 6", False, False, True, 4],
    ["ocean crossing 7", False, False, False, 4],
    ["ocean crossing 8", False, False, False, 4],
    ["ocean crossing NG+", False, False, False, 5],
    ["ocean crossing NG+ 2", False, False, False, 5],
    ["ocean crossing NG+ 3", False, True, False, 5],
    ["worm", False, False, False, 5],
    ["worm 2", False, False, False, 5],
    ["worm 3", False, False, False, 5],
    ["worm 4", False, True, False, 5],
    ["worm 5", False, False, False, 5],
    ["worm 6", False, False, False, 5],
    ["worm 7", False, False, False, 5],
    ["worm 8", False, False, False, 5],
    ["worm 9", False, False, False, 5],
    ["worm 10", False, False, False, 6],
    ["worm ng+", True, False, False, 6],
    ["worm ng+ 2", False, False, False, 6],
    ["exploration", False, False, False, 6],
    ["exploration 2", False, False, False, 6],
    ["exploration 3", False, False, False, 6],
    ["convergence", False, False, False, 6],
    ["hunter", False, False, False, 7],
    ["hunter 2", False, False, False, 7],
    ["hunter 3", False, False, False, 7],
    ["hunter 4", True, False, False, 7],
    ["hunter 5", False, False, False, 7],
    ["analysis", False, False, False, 8],
    ["analysis 2", True, False, True, 8],
    ["escape", False, True, False, 8],
    ["escape 2", False, True, False, 8],
    ["escape 3", False, False, False, 8],
    ["escape 4", False, False, False, 8],
    ["escape 5", False, False, False, 8],
    ["escape 6", False, False, False, 8],
    ["escape 7", False, False, True, 8],
    ["ending", False, False, False, 9],
    ["ending 2", False, False, False, 9],
    ["ending 3", False, False, False, 9],
] + \
["os tuning"] * 10 + \
['Arena F', 'Arena E', 'Arena D', 'Arena C', 'Arena B', 'Arena A', 'Arena S'] + \
['Chapter 1', 'Chapter 2', 'Chapter 3', 'Chapter 4', 'Chapter 5', 'NG+', 'NG++']
