from BaseClasses import Location


class ArmoredCore6Location(Location):
    game = "Armored Core 6"


locations = [
    [ 'Illegal Entry', "mission", "Chapter 1", [  ] ],
    [ 'Destroy Artillery Installations', "mission", "Chapter 1", [  ] ],
    [ 'Grid 135 Cleanup', "mission", "Chapter 1", [  ] ],
    [ 'Destroy the Transport Helicopters', "mission", "Chapter 1", [  ] ],
    [ 'Destroy the Tester AC', "mission", "Chapter 1", [  ] ],
    [ 'Attack the Dam Complex', "mission", "Chapter 1", [  ] ],
    [ 'Destroy the Weaponized Mining Ship', "mission", "Chapter 1", [  ] ],
    [ 'Operation Wallclimber', "mission", "Chapter 1", [ "tier 2" ] ],
    [ 'Retrieve Combat Logs', "mission", "Chapter 1", [ "tier 2" ] ],
    [ 'Investigate BAWS Arsenal No. 2', "mission", "Chapter 1", [ "tier 2" ] ],
    [ 'Attack the Watchpoint', "mission", "Chapter 1", [ "competent_anti_shield","tier 2" ] ],
    [ 'Infiltrate Grid 086', "mission", "Chapter 2", [ "tier 2" ] ],
    [ 'Eliminate the Doser Faction', "mission", "Chapter 2", [ "tier 2" ] ],
    [ 'Ocean Crossing', "mission", "Chapter 2", [ "competent_impact","tier 3" ] ],
    [ 'Steal the Survey Data', "mission", "Chapter 3", [ "tier 3" ] ],
    [ 'Attack the Refueling Base', "mission", "Chapter 3", [ "tier 3" ] ],
    [ 'Eliminate V.VII', "mission", "Chapter 3", [ "tier 3" ] ],
    [ 'Tunnel Sabotage', "mission", "Chapter 3", [ "tier 3" ] ],
    [ 'Survey the Uninhabited Floating City', "mission", "Chapter 3", [ "tier 3" ] ],
    [ 'Heavy Missile Launch Support', "mission", "Chapter 3", [ "tier 3" ] ],
    [ 'Eliminate the Enforcement Squads', "mission", "Chapter 3", [ "tier 4" ] ],
    [ 'Destroy Special Forces', "mission", "Chapter 3", [ "competent_tank","tier 3" ] ],
    [ 'Attack the Old Spaceport', "mission", "Chapter 3", [ "tier 3" ] ],
    [ 'Eliminate "Honest" Brute', "mission", "Chapter 3", [ "tier 3" ] ],
    [ 'Defend the Old Spaceport', "mission", "Chapter 3", [ "tier 3" ] ],
    [ 'Historic Data Recovery', "mission", "Chapter 3", [  ] ],
    [ 'Destroy the Ice Worm', "mission", "Chapter 3", [ "tier 3","VE-60SNA" ] ],
    [ 'Underground Exploration - Depth 1', "mission", "Chapter 4", [ "tier 3" ] ],
    [ 'Underground Exploration - Depth 2', "mission", "Chapter 4", [ "tier 4" ] ],
    [ 'Underground Exploration - Depth 3', "mission", "Chapter 4", [ "tier 5" ] ],
    [ 'Intercept the Redguns', "mission", "Chapter 4", [ "competent_tank","tier 5" ] ],
    [ 'Ambus the Vespers', "mission", "Chapter 4", [ "tier 5" ] ],
    [ 'Unknown Territory Survey', "mission", "Chapter 4", [ "tier 5" ] ],
    [ 'Reach the Coral Convergence', "mission", "Chapter 4", [ "tier 5" ] ],
    [ 'Escape', "mission", "Chapter 5", [  ] ],
    [ 'Take the Uninhabited Floating City', "mission", "Chapter 5", [ "tier 5" ] ],
    [ 'Intercept the Corporate Forces', "mission", "Chapter 5", [ "tier 6" ] ],
    [ 'Eliminate "Cinder" Carla', "mission", "Chapter 5", [ "competent_tank","tier 6" ] ],
    [ 'Breach the Karman Line', "mission", "Chapter 5", [ "tier 6" ] ],
    [ 'Destroy the Drive Block', "mission", "Chapter 5", [ "competent_anti_shield","tier 6" ] ],
    [ 'Shut Down the Closure Satellites', "mission", "Chapter 5", [ "competent_anti_shield","tier 7" ] ],
    [ 'Bring Down the Xylem', "mission", "Chapter 5", [ "tier 7" ] ],
    [ 'Attack the Dam Complex (alt)', "mission", "NG+", [ "tier 2" ] ],
    [ 'Prevent Corporate Salvage of New Tech (alt)', "mission", "NG+", [ "tier 5" ] ],
    [ 'Defend the Dam Complex (alt)', "mission", "NG+", [ "tier 7" ] ],
    [ 'Escort the Weaponized Mining Ship (alt)', "mission", "NG++", [ "competent_tank","tier 8" ] ],
    [ 'Prisoner Rescue (alt)', "mission", "NG++", [ "tier 7" ] ],
    [ 'Obstruct the Mandatory Inspection (alt)', "mission", "NG++", [ "competent_impact","competent_tank","tier 8" ] ],
    [ 'Attack the Watchpoint (alt)', "mission", "NG++", [ "competent_anti_shield","tier 6" ] ],
    [ 'Stop the Secret Data Breach (alt)', "mission", "NG++", [ "tier 6" ] ],
    [ 'Survey the Uninhabited Floating City (alt)', "mission", "NG++", [ "tier 6" ] ],
    [ 'Coral Export Denial (alt)', "mission", "NG++", [ "tier 7" ] ],
    [ 'Underground Exploration - Depth 2 (alt)', "mission", "NG++", [ "tier 7" ] ],
    [ 'Eliminate V.III (alt)', "mission", "NG++", [ "tier 7" ] ],
    [ 'Unknown Territory Survey (alt)', "mission", "NG++", [ "tier 7" ] ],
    [ 'Reach the Coral Convergence (alt)', "mission", "NG++", [ "competent_anti_shield","tier 8" ] ],
    [ 'MIA (alt)', "mission", "NG++", [ "competent_impact","tier 8" ] ],
    [ 'Regain Control of the Xylem (alt)', "mission", "NG++", [ "tier 9" ] ],
    [ 'Coral Release (alt)', "mission", "NG++", [ "tier 9" ] ],
    [ '"Invincible" Rummy', "arena", "F" ],
    [ 'Index Dunham', "arena", "F" ],
    [ 'G6 Red', "arena", "F" ],
    [ 'Nosaac', "arena", "E" ],
    [ 'V.VI Maeterlinck', "arena", "E" ],
    [ 'Little Ziyi', "arena", "E" ],
    [ 'V.VII Swinburne', "arena", "E" ],
    [ 'G3 Wu Huahai', "arena", "D" ],
    [ 'Ring Freddie', "arena", "D" ],
    [ 'V.V Hawkins', "arena", "D" ],
    [ 'G5 Iguazu', "arena", "D" ],
    [ 'Rokumonsen', "arena", "D" ],
    [ 'G4 Volta', "arena", "D" ],
    [ 'V.VIII Pater', "arena", "C" ],
    [ 'Sulla', "arena", "C" ],
    [ '"Chatty" Stick', "arena", "C" ],
    [ 'Middle Flatwell', "arena", "C" ],
    [ 'V.III O\'Keeffe', "arena", "B" ],
    [ '"Cinder" Carla', "arena", "B" ],
    [ 'Coldcall', "arena", "B" ],
    [ 'V.IV Rusty', "arena", "B" ],
    [ '"Honest" Brute', "arena", "B" ],
    [ 'G2 Nile', "arena", "A" ],
    [ 'V.II Snail', "arena", "A" ],
    [ 'Chartreuse', "arena", "A" ],
    [ 'Thumb Dolmayan', "arena", "A" ],
    [ 'King', "arena", "A" ],
    [ 'G1 Michigan', "arena", "S" ],
    [ 'V.I Freud', "arena", "S" ],
]
